//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Resx {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class All {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal All() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Resx.All", typeof(All).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Register に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BUTTON_REGISTER {
            get {
                return ResourceManager.GetString("BUTTON REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Autumn に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ESEASON_AUTUMN {
            get {
                return ResourceManager.GetString("ESEASON_AUTUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spring に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ESEASON_SPRING {
            get {
                return ResourceManager.GetString("ESEASON_SPRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ESEASON_SUMMER {
            get {
                return ResourceManager.GetString("ESEASON_SUMMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Winter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ESEASON_WINTER {
            get {
                return ResourceManager.GetString("ESEASON_WINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LANGUAGE_SELECTS {
            get {
                return ResourceManager.GetString("LANGUAGE_SELECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I like season: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PAGE_ENUM_ILIKESEASON {
            get {
                return ResourceManager.GetString("PAGE_ENUM_ILIKESEASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;h2&gt;Validation of Accept-Language&lt;/h2&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PAGE_H_ACCEPTLANG {
            get {
                return ResourceManager.GetString("PAGE_H_ACCEPTLANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enum Test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PAGE_TITLE_ENUM {
            get {
                return ResourceManager.GetString("PAGE_TITLE_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home(Neutral) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PAGE_TITLE_HOME {
            get {
                return ResourceManager.GetString("PAGE_TITLE_HOME", resourceCulture);
            }
        }
    }
}
